[#187082048] Add Django 4 compatibility
HousekeepLtd/django-blog-zinnia pull request #4
Opened 2024-06-17 13:10 UTC by mrmikardo

# Proposed changes

This PR adds Django 4 support to the Housekeep fork of [the original Zinnia project](https://github.com/Fantomas42/django-blog-zinnia), which has not been maintained for several years.

A summary of the changes made here is:

- Bump the Django version specified in the `setup.py` to be at least 4.0.0
- Cut the `django-tagging` dependency from `setup.py`: `django-tagging` is another unmaintained package which doesn't support Django 4. A [Housekeep-specific fork](https://github.com/HousekeepLtd/django-tagging) of this package has been created, which (i) supports Django 4 and (ii) fixes some other (maybe Django-4 related?) bugs.
- Fix some outdated imports in the demo project: this means it actually runs and can be used to test the project!
- Update some Python 2 specific code (object inheritance, `__future__` imports)

Note that the change to the `django-tagging` dependency means that from now on, we'll have to list that dependency in the main Housekeep repo's Pipfile.

2024-06-17 13:14 UTC, mrmikardo commented on demo/manage.py
Added this file as using `django-admin` is annoying (you have to manually specify the settings module path).

2024-06-17 13:14 UTC, mrmikardo commented on demo/settings.py
> -    ('zh-hans', gettext('Simplified Chinese')),
We don't support any of these languages, and they were causing issues when I bumped to Django 4: ✂️ .

2024-06-17 13:15 UTC, mrmikardo commented on zinnia/templates/zinnia/entry_list.html
Change in this file updates a tag which [has been deprecated](https://code.djangoproject.com/ticket/31532).

2024-06-19 15:24 UTC, horthbynorthwest requested changes
only additional thing we should do is bump the version like we fixed in #3 (and initially changed in #2)

2024-06-19 15:24 UTC, horthbynorthwest commented on demo/settings.py
> -    ('zh-hans', gettext('Simplified Chinese')),
Makes sense, time to get them gone!

2024-06-19 15:24 UTC, horthbynorthwest commented on zinnia/tests/implementations/urls/custom_detail_views.py
> -from django.conf.urls import url
was this just a left over unused import, I can't see where this was used in this file?

2024-06-19 15:24 UTC, horthbynorthwest commented on zinnia/tests/implementations/urls/default.py
> -from django.conf.urls import url
same here

2024-06-20 11:30 UTC, horthbynorthwest approved these changes
😎

2024-06-20 13:59 UTC, merged